# conf/config.yaml
defaults:
  - llm: qwen-3
  - agent: mirothinker_v1.5_keep5_max200
  - benchmark: default
  - _self_  # Allows variables to be defined at the top of this file

hydra:
  run:
    dir: ../../logs/debug

# You can define some top-level or default parameters here
project_name: "miroflow-agent"
debug_dir: "../../logs/debug"
